In [1]:
import pandas as pd
import matplotlib
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline  

import calendar
from __future__ import division

In [6]:
train = pd.read_csv("train.csv")
test = pd.read_csv("test.csv")

In [4]:
#train.columns = ["Day", "Month", "Year", "City", "Count"]
#test.columns = ["Day", "Month", "Year", "City"]

In [5]:
#6 городов отсутвуют в тестовой выборке - удалим их из тренировочной
print len(train.City.unique())
print len(test.City.unique())
a = set(train.City.unique()) - (set(train.City.unique()) & set(test.City.unique()))
for i in a:
    print i
    train = train[train.City != i]

114
114

In [7]:
train

,Day,Month,Year,City,Count,WeekDay,DayForStartYear,isWeekend,DayForStartTrainPeriod
0,6,10,2011,Сыктывкар-1,8,3,278,0,0
1,7,10,2011,Сыктывкар-1,88,4,279,0,1
2,9,10,2011,Сыктывкар-1,1,6,281,1,3
3,15,11,2011,Сыктывкар-1,1,1,318,0,40
4,8,12,2011,Сыктывкар-1,2,3,341,0,63
5,9,12,2011,Сыктывкар-1,43,4,342,0,64
6,10,12,2011,Сыктывкар-1,10,5,343,1,65
7,11,12,2011,Сыктывкар-1,1,6,344,1,66
8,13,12,2011,Сыктывкар-1,60,1,346,0,68
9,15,12,2011,Сыктывкар-1,96,3,348,0,70
10,16,12,2011,Сыктывкар-1,134,4,349,0,71
11,17,12,2011,Сыктывкар-1,112,5,350,1,72
12,18,12,2011,Сыктывкар-1,100,6,351,1,73
13,20,12,2011,Сыктывкар-1,73,1,353,0,75
14,21,12,2011,Сыктывкар-1,94,2,354,0,76
15,22,12,2011,Сыктывкар-1,94,3,355,0,77
16,23,12,2011,Сыктывкар-1,129,4,356,0,78
17,24,12,2011,Сыктывкар-1,164,5,357,1,79
18,25,12,2011,Сыктывкар-1,122,6,358,1,80
19,28,12,2011,Сыктывкар-1,128,2,361,0,83
20,29,12,2011,Сыктывкар-1,172,3,362,0,84
21,30,12,2011,Сыктывкар-1,223,4,363,0,85
22,31,12,2011,Сыктывкар-1,68,5,364,1,86
23,1,1,2012,Сыктывкар-1,100,6,0,1,87
24,2,1,2012,Сыктывкар-1,169,0,1,0,88
25,3,1,2012,Сыктывкар-1,142,1,2,0,89
26,4,1,2012,Сыктывкар-1,130,2,3,0,90
27,5,1,2012,Сыктывкар-1,119,3,4,0,91
28,6,1,2012,Сыктывкар-1,128,4,5,0,92
29,7,1,2012,Сыктывкар-1,128,5,6,1,93
...,...,...,...,...,...,...,...,...,...
46018,19,10,2016,Самара-1,240,2,292,0,1840
46019,19,10,2016,Уфа-1,98,2,292,0,1840
46020,19,10,2016,Челябинск-1,127,2,292,0,1840
46021,19,10,2016,Радужный-1,46,2,292,0,1840
46022,19,10,2016,Домодедово-1,65,2,292,0,1840
46023,19,10,2016,Балашиха-1,105,2,292,0,1840
46024,19,10,2016,Волжский-1,86,2,292,0,1840
46025,19,10,2016,Альметьевск-1,58,2,292,0,1840
46026,19,10,2016,Тюмень-2,117,2,292,0,1840
46027,19,10,2016,Абакан-1,56,2,292,0,1840
46028,19,10,2016,Саратов-1,178,2,292,0,1840
46029,19,10,2016,Новороссийск-1,125,2,292,0,1840
46030,19,10,2016,Выборг-1,81,2,292,0,1840
46031,19,10,2016,Екатеринбург-1,78,2,292,0,1840
46032,19,10,2016,Зеленокумск-1,36,2,292,0,1840
46033,19,10,2016,Реутов-1,95,2,292,0,1840
46034,19,10,2016,Самара-4,190,2,292,0,1840
46035,19,10,2016,Ульяновск-1,111,2,292,0,1840
46036,19,10,2016,Сыктывкар-4,33,2,292,0,1840
46037,19,10,2016,Зеленоград-1,139,2,292,0,1840
46038,19,10,2016,Москва 1-1,69,2,292,0,1840
46039,19,10,2016,Уссурийск-1,130,2,292,0,1840
46040,19,10,2016,Энгельс-1,48,2,292,0,1840
46041,19,10,2016,Абинск-1,43,2,292,0,1840
46042,19,10,2016,Смоленск-3,39,2,292,0,1840
46043,19,10,2016,Москва 1-5,75,2,292,0,1840
46044,19,10,2016,Чайковский-1,41,2,292,0,1840
46045,19,10,2016,Челябинск-2,134,2,292,0,1840
46046,19,10,2016,Ангарск-1,68,2,292,0,1840
46047,19,10,2016,Железнодорожный-1,105,2,292,0,1840

In [7]:
train.describe()

,Day,Month,Year,Count,WeekDay,DayForStartYear
count,46048.000000,46048.000000,46048.000000,46048.000000,46048.000000,46048.000000
mean,15.455916,6.606888,2015.200595,106.113447,2.998632,184.598484
std,8.732700,3.191562,1.008963,76.608338,1.994862,97.411710
min,1.000000,1.000000,2011.000000,1.000000,0.000000,0.000000
25%,8.000000,4.000000,2015.000000,55.000000,1.000000,103.000000
50%,15.000000,7.000000,2016.000000,87.000000,3.000000,192.000000
75%,23.000000,9.000000,2016.000000,135.000000,5.000000,262.000000
max,31.000000,12.000000,2016.000000,2044.000000,6.000000,364.000000

In [7]:
res = []
for i in train.axes[0]:
    a = calendar.datetime.date(train.Year[i], train.Month[i], train.Day[i])
    res.append(a.weekday())
train["WeekDay"] = pd.Series(res)

In [8]:
res = []
for i in test.axes[0]:
    a = calendar.datetime.date(test.Year[i], test.Month[i], test.Day[i])
    res.append(a.weekday())
test["WeekDay"] = pd.Series(res)

In [14]:
train.head()

   Day  Month  Year           City  Count  WeekDay
0    8      8  2016  Лениногорск-1     42        0
1    7      3  2015       Абакан-1     81        5
2    5     10  2016       Тюмень-1    138        2
3   22      2  2015  Октябрьский-1     94        6
4    6      8  2016     Нахабино-1     42        5

In [18]:
cityDescribe = pd.DataFrame()
cityDescribe["name"] = train.City.unique()
cityDescribe["population"] = range(len(train.City.unique()))

In [50]:
trainNew = train.copy()
i = 0
for j in train.DayForStartTrainPeriod.sort_values().index:
    trainNew.loc[i] = train.loc[j]
    i += 1
    if ((i % 100) == 0):
        print i,
trainNew.to_csv("train.csv", index=None)

100 200 300 400 500 600 700 800 900 1000 1100 1200 1300 1400 1500 1600 1700 1800 1900 2000 2100 2200 2300 2400 2500 2600 2700 2800 2900 3000 3100 3200 3300 3400 3500 3600 3700 3800 3900 4000 4100 4200 4300 4400 4500 4600 4700 4800 4900 5000 5100 5200 5300 5400 5500 5600 5700 5800 5900 6000 6100 6200 6300 6400 6500 6600 6700 6800 6900 7000 7100 7200 7300 7400 7500 7600 7700 7800 7900 8000 8100 8200 8300 8400 8500 8600 8700 8800 8900 9000 9100 9200 9300 9400 9500 9600 9700 9800 9900 10000 10100 10200 10300 10400 10500 10600 10700 10800 10900 11000 11100 11200 11300 11400 11500 11600 11700 11800 11900 12000 12100 12200 12300 12400 12500 12600 12700 12800 12900 13000 13100 13200 13300 13400 13500 13600 13700 13800 13900 14000 14100 14200 14300 14400 14500 14600 14700 14800 14900 15000 15100 15200 15300 15400 15500 15600 15700 15800 15900 16000 16100 16200 16300 16400 16500 16600 16700 16800 16900 17000 17100 17200 17300 17400 17500 17600 17700 17800 17900 18000 18100 18200 18300 18400 18500 18600 18700 18800 18900 19000 19100 19200 19300 19400 19500 19600 19700 19800 19900 20000 20100 20200 20300 20400 20500 20600 20700 20800 20900 21000 21100 21200 21300 21400 21500 21600 21700 21800 21900 22000 22100 22200 22300 22400 22500 22600 22700 22800 22900 23000 23100 23200 23300 23400 23500 23600 23700 23800 23900 24000 24100 24200 24300 24400 24500 24600 24700 24800 24900 25000 25100 25200 25300 25400 25500 25600 25700 25800 25900 26000 26100 26200 26300 26400 26500 26600 26700 26800 26900 27000 27100 27200 27300 27400 27500 27600 27700 27800 27900 28000 28100 28200 28300 28400 28500 28600 28700 28800 28900 29000 29100 29200 29300 29400 29500 29600 29700 29800 29900 30000 30100 30200 30300 30400 30500 30600 30700 30800 30900 31000 31100 31200 31300 31400 31500 31600 31700 31800 31900 32000 32100 32200 32300 32400 32500 32600 32700 32800 32900 33000 33100 33200 33300 33400 33500 33600 33700 33800 33900 34000 34100 34200 34300 34400 34500 34600 34700 34800 34900 35000 35100 35200 35300 35400 35500 35600 35700 35800 35900 36000 36100 36200 36300 36400 36500 36600 36700 36800 36900 37000 37100 37200 37300 37400 37500 37600 37700 37800 37900 38000 38100 38200 38300 38400 38500 38600 38700 38800 38900 39000 39100 39200 39300 39400 39500 39600 39700 39800 39900 40000 40100 40200 40300 40400 40500 40600 40700 40800 40900 41000 41100 41200 41300 41400 41500 41600 41700 41800 41900 42000 42100 42200 42300 42400 42500 42600 42700 42800 42900 43000 43100 43200 43300 43400 43500 43600 43700 43800 43900 44000 44100 44200 44300 44400 44500 44600 44700 44800 44900 45000 45100 45200 45300 45400 45500 45600 45700 45800 45900 46000

In [51]:
testNew = test.copy()
i = 0
for j in test.DayForStartTrainPeriod.sort_values().index:
    testNew.loc[i] = test.loc[j]
    i += 1
    if ((i % 100) == 0):
        print i,
testNew.to_csv("test.csv", index=None)

100 200 300 400 500 600 700 800 900 1000 1100 1200 1300 1400 1500 1600 1700 1800 1900 2000 2100 2200 2300 2400 2500 2600 2700 2800 2900 3000 3100 3200 3300 3400 3500 3600 3700 3800 3900 4000 4100 4200 4300 4400 4500 4600 4700 4800 4900 5000 5100 5200 5300 5400 5500 5600 5700 5800 5900 6000 6100 6200 6300 6400 6500 6600 6700 6800 6900 7000 7100 7200 7300

In [59]:
'''
top = calendar.datetime.date(3000, 10, 10)
topIndex = None
down = calendar.datetime.date(1000, 10, 10)
downIndex = None

currentDate = calendar.datetime.date(year, month, day)

for i in X_train[(X_train.City == city)].index:
    tmpDay = calendar.datetime.date(X_train.Year[i], X_train.Month[i], X_train.Day[i])
    if((tmpDay > currentDate) & (tmpDay < top)):
        top = tmpDay
        topIndex = i
    if((tmpDay < currentDate) & (tmpDay > down)):
        down = tmpDay
        downIndex = i

count = 0
if(topIndex == None):
    count = y_train[downIndex]
if(downIndex == None):
    count = y_train[topIndex]
if((downIndex != None) & (topIndex != None)):
    allInter = (top - down).days
    downInter = (currentDate - down).days
    topInter = (top - currentDate).days
    count = (topInter/allInter) * y_train[topIndex] + (downInter/allInter) * y_train[downIndex]
return count

allInter = (top - down).days
downInter = (currentDate - down).days
topInter = (top - currentDate).days
'''

'\ntop = calendar.datetime.date(3000, 10, 10)\ntopIndex = None\ndown = calendar.datetime.date(1000, 10, 10)\ndownIndex = None\n\ncurrentDate = calendar.datetime.date(year, month, day)\n\nfor i in X_train[(X_train.City == city)].index:\n    tmpDay = calendar.datetime.date(X_train.Year[i], X_train.Month[i], X_train.Day[i])\n    if((tmpDay > currentDate) & (tmpDay < top)):\n        top = tmpDay\n        topIndex = i\n    if((tmpDay < currentDate) & (tmpDay > down)):\n        down = tmpDay\n        downIndex = i\n\ncount = 0\nif(topIndex == None):\n    count = y_train[downIndex]\nif(downIndex == None):\n    count = y_train[topIndex]\nif((downIndex != None) & (topIndex != None)):\n    allInter = (top - down).days\n    downInter = (currentDate - down).days\n    topInter = (top - currentDate).days\n    count = (topInter/allInter) * y_train[topIndex] + (downInter/allInter) * y_train[downIndex]\nreturn count\n\nallInter = (top - down).days\ndownInter = (currentDate - down).days\ntopInter = (top - currentDate).days\n'

In [5]:
def GetCountDayForStarYear(year, month, day):
    day = calendar.datetime.date(year, month, day)
    dayStartYear = calendar.datetime.date(year, 1, 1)
    
    return int((day - dayStartYear).days)

In [6]:
train["DayForStartYear"] = None


res = []
for i in range(len(train.index)):
    res.append(GetCountDayForStarYear(train.Year[i], train.Month[i], train.Day[i]))
train["DayForStartYear"] = pd.Series(res)

In [7]:
test["DayForStartYear"] = None


res = []
for i in range(len(test.index)):
    res.append(GetCountDayForStarYear(test.Year[i], test.Month[i], test.Day[i]))
test["DayForStartYear"] = pd.Series(res)

In [4]:
train

,Day,Month,Year,City,Count,WeekDay,DayForStartYear,isWeekend,DayForStartTrainPeriod
0,6,10,2011,Сыктывкар-1,8,3,278,0,0
1,7,10,2011,Сыктывкар-1,88,4,279,0,1
2,9,10,2011,Сыктывкар-1,1,6,281,1,3
3,15,11,2011,Сыктывкар-1,1,1,318,0,40
4,8,12,2011,Сыктывкар-1,2,3,341,0,63
5,9,12,2011,Сыктывкар-1,43,4,342,0,64
6,10,12,2011,Сыктывкар-1,10,5,343,1,65
7,11,12,2011,Сыктывкар-1,1,6,344,1,66
8,13,12,2011,Сыктывкар-1,60,1,346,0,68
9,15,12,2011,Сыктывкар-1,96,3,348,0,70
10,16,12,2011,Сыктывкар-1,134,4,349,0,71
11,17,12,2011,Сыктывкар-1,112,5,350,1,72
12,18,12,2011,Сыктывкар-1,100,6,351,1,73
13,20,12,2011,Сыктывкар-1,73,1,353,0,75
14,21,12,2011,Сыктывкар-1,94,2,354,0,76
15,22,12,2011,Сыктывкар-1,94,3,355,0,77
16,23,12,2011,Сыктывкар-1,129,4,356,0,78
17,24,12,2011,Сыктывкар-1,164,5,357,1,79
18,25,12,2011,Сыктывкар-1,122,6,358,1,80
19,28,12,2011,Сыктывкар-1,128,2,361,0,83
20,29,12,2011,Сыктывкар-1,172,3,362,0,84
21,30,12,2011,Сыктывкар-1,223,4,363,0,85
22,31,12,2011,Сыктывкар-1,68,5,364,1,86
23,1,1,2012,Сыктывкар-1,100,6,0,1,87
24,2,1,2012,Сыктывкар-1,169,0,1,0,88
25,3,1,2012,Сыктывкар-1,142,1,2,0,89
26,4,1,2012,Сыктывкар-1,130,2,3,0,90
27,5,1,2012,Сыктывкар-1,119,3,4,0,91
28,6,1,2012,Сыктывкар-1,128,4,5,0,92
29,7,1,2012,Сыктывкар-1,128,5,6,1,93
...,...,...,...,...,...,...,...,...,...
46018,19,10,2016,Самара-1,240,2,292,0,1840
46019,19,10,2016,Уфа-1,98,2,292,0,1840
46020,19,10,2016,Челябинск-1,127,2,292,0,1840
46021,19,10,2016,Радужный-1,46,2,292,0,1840
46022,19,10,2016,Домодедово-1,65,2,292,0,1840
46023,19,10,2016,Балашиха-1,105,2,292,0,1840
46024,19,10,2016,Волжский-1,86,2,292,0,1840
46025,19,10,2016,Альметьевск-1,58,2,292,0,1840
46026,19,10,2016,Тюмень-2,117,2,292,0,1840
46027,19,10,2016,Абакан-1,56,2,292,0,1840
46028,19,10,2016,Саратов-1,178,2,292,0,1840
46029,19,10,2016,Новороссийск-1,125,2,292,0,1840
46030,19,10,2016,Выборг-1,81,2,292,0,1840
46031,19,10,2016,Екатеринбург-1,78,2,292,0,1840
46032,19,10,2016,Зеленокумск-1,36,2,292,0,1840
46033,19,10,2016,Реутов-1,95,2,292,0,1840
46034,19,10,2016,Самара-4,190,2,292,0,1840
46035,19,10,2016,Ульяновск-1,111,2,292,0,1840
46036,19,10,2016,Сыктывкар-4,33,2,292,0,1840
46037,19,10,2016,Зеленоград-1,139,2,292,0,1840
46038,19,10,2016,Москва 1-1,69,2,292,0,1840
46039,19,10,2016,Уссурийск-1,130,2,292,0,1840
46040,19,10,2016,Энгельс-1,48,2,292,0,1840
46041,19,10,2016,Абинск-1,43,2,292,0,1840
46042,19,10,2016,Смоленск-3,39,2,292,0,1840
46043,19,10,2016,Москва 1-5,75,2,292,0,1840
46044,19,10,2016,Чайковский-1,41,2,292,0,1840
46045,19,10,2016,Челябинск-2,134,2,292,0,1840
46046,19,10,2016,Ангарск-1,68,2,292,0,1840
46047,19,10,2016,Железнодорожный-1,105,2,292,0,1840

In [31]:
res = [0] * len(train.index)
for i in range(len(train.index)):
    if((calendar.datetime.date(train.Year[i], train.Month[i], train.Day[i]).weekday() == 5) |\
       (calendar.datetime.date(train.Year[i], train.Month[i], train.Day[i]).weekday() == 6)):
        res[i] = 1
train["isWeekend"] = pd.Series(res)

In [33]:
res = [0] * len(test.index)
for i in range(len(test.index)):
    if((calendar.datetime.date(test.Year[i], test.Month[i], test.Day[i]).weekday() == 5) |\
       (calendar.datetime.date(test.Year[i], test.Month[i], test.Day[i]).weekday() == 6)):
        res[i] = 1
test["isWeekend"] = pd.Series(res)

In [35]:
#6.10.2011

In [43]:
def DayForStartTrainPeriod(data):
    res = [0] * len(data.index)
    startDate = calendar.datetime.date(2011, 10, 6)
    for i in range(len(data.index)):
        currentDay = calendar.datetime.date(data.Year[i], data.Month[i], data.Day[i])
        res[i] = (currentDay - startDate).days
    return res

In [47]:
res = DayForStartTrainPeriod(train)
train["DayForStartTrainPeriod"] = pd.Series(res)
res = DayForStartTrainPeriod(test)
test["DayForStartTrainPeriod"] = pd.Series(res)

In [5]:
def MeanNDayFromThis(n, data, City, Year, Month, Day):
    data = data[data.City == City]
    indexArray = data.index
    step = 1 if n > 0 else -1


    startIndex = data[(data.City == City) & (data.Year == Year) & (data.Month == Month) & (data.Day == Day)].index
    startIndex = startIndex.astype(int)[0]


    startI = indexArray.tolist().index(startIndex)
    start = startI + step
    
    if((startI == 0) & (n < 0) ):
        return -100000
    
    if((startI == (len(indexArray) - 1)) & (n > 0)):
        return 100000
    
    if(n > 0):
        end = (start + n - step)  if ( (start + n - step) < len(indexArray)) else len(indexArray) - 1

    if(n < 0):
        end = (start + n + step)  if ( (start + n + step) >= 0) else 0

    startTime = calendar.datetime.date(Year, Month, Day)

    count = 0
    mean = 0

    k = 0

    for i in range(start, end, step):
        year = data.Year[indexArray[i]]
        month = data.Month[indexArray[i]]
        day = data.Day[indexArray[i]]
        if( abs((calendar.datetime.date(year, month, day) - startTime).days) <= abs(n) ):
            mean += data.Count[indexArray[i]]
            count += 1
        else:
            break

    if( (n < 0) & (count == 0) ):
        return -100000 * 10
    
    if( (n > 0)  & (count == 0) ):
        return 100000 * 10
    
    res = mean / count
    
    return res
    #так как я в основном использую деревья для решений, то при ситуации, когда не будет значений перед текущей датой, 
    #я буду присваивать ей большое положительное знание, если сзади нет, то большое отрицательное, с целью, чтобы данные значения 
    #уходили в отдельный лист дерева

In [97]:
n = 7
res = []
k = 0
for i in range(len(train)):
    res.append(MeanNDayFromThis(n, train, train.City[i], train.Year[i], train.Month[i], train.Day[i]))
    if ( (k % 100) == 0):
        print k,
    k += 1
train["MeanNext7Day"] = pd.Series(res)

0 100 200 300 400 500 600 700 800 900 1000 1100 1200 1300 1400 1500 1600 1700 1800 1900 2000 2100 2200 2300 2400 2500 2600 2700 2800 2900 3000 3100 3200 3300 3400 3500 3600 3700 3800 3900 4000 4100 4200 4300 4400 4500 4600 4700 4800 4900 5000 5100 5200 5300 5400 5500 5600 5700 5800 5900 6000 6100 6200 6300 6400 6500 6600 6700 6800 6900 7000 7100 7200 7300 7400 7500 7600 7700 7800 7900 8000 8100 8200 8300 8400 8500 8600 8700 8800 8900 9000 9100 9200 9300 9400 9500 9600 9700 9800 9900 10000 10100 10200 10300 10400 10500 10600 10700 10800 10900 11000 11100 11200 11300 11400 11500 11600 11700 11800 11900 12000 12100 12200 12300 12400 12500 12600 12700 12800 12900 13000 13100 13200 13300 13400 13500 13600 13700 13800 13900 14000 14100 14200 14300 14400 14500 14600 14700 14800 14900 15000 15100 15200 15300 15400 15500 15600 15700 15800 15900 16000 16100 16200 16300 16400 16500 16600 16700 16800 16900 17000 17100 17200 17300 17400 17500 17600 17700 17800 17900 18000 18100 18200 18300 18400 18500 18600 18700 18800 18900 19000 19100 19200 19300 19400 19500 19600 19700 19800 19900 20000 20100 20200 20300 20400 20500 20600 20700 20800 20900 21000 21100 21200 21300 21400 21500 21600 21700 21800 21900 22000 22100 22200 22300 22400 22500 22600 22700 22800 22900 23000 23100 23200 23300 23400 23500 23600 23700 23800 23900 24000 24100 24200 24300 24400 24500 24600 24700 24800 24900 25000 25100 25200 25300 25400 25500 25600 25700 25800 25900 26000 26100 26200 26300 26400 26500 26600 26700 26800 26900 27000 27100 27200 27300 27400 27500 27600 27700 27800 27900 28000 28100 28200 28300 28400 28500 28600 28700 28800 28900 29000 29100 29200 29300 29400 29500 29600 29700 29800 29900 30000 30100 30200 30300 30400 30500 30600 30700 30800 30900 31000 31100 31200 31300 31400 31500 31600 31700 31800 31900 32000 32100 32200 32300 32400 32500 32600 32700 32800 32900 33000 33100 33200 33300 33400 33500 33600 33700 33800 33900 34000 34100 34200 34300 34400 34500 34600 34700 34800 34900 35000 35100 35200 35300 35400 35500 35600 35700 35800 35900 36000 36100 36200 36300 36400 36500 36600 36700 36800 36900 37000 37100 37200 37300 37400 37500 37600 37700 37800 37900 38000 38100 38200 38300 38400 38500 38600 38700 38800 38900 39000 39100 39200 39300 39400 39500 39600 39700 39800 39900 40000 40100 40200 40300 40400 40500 40600 40700 40800 40900 41000 41100 41200 41300 41400 41500 41600 41700 41800 41900 42000 42100 42200 42300 42400 42500 42600 42700 42800 42900 43000 43100 43200 43300 43400 43500 43600 43700 43800 43900 44000 44100 44200 44300 44400 44500 44600 44700 44800 44900 45000 45100 45200 45300 45400 45500 45600 45700 45800 45900 46000

,Day,Month,Year,City,Count,WeekDay,DayForStartYear,isWeekend,DayForStartTrainPeriod
0,6,10,2011,Сыктывкар-1,8,3,278,0,0
1,7,10,2011,Сыктывкар-1,88,4,279,0,1
2,9,10,2011,Сыктывкар-1,1,6,281,1,3
3,15,11,2011,Сыктывкар-1,1,1,318,0,40
4,8,12,2011,Сыктывкар-1,2,3,341,0,63
5,9,12,2011,Сыктывкар-1,43,4,342,0,64
6,10,12,2011,Сыктывкар-1,10,5,343,1,65
7,11,12,2011,Сыктывкар-1,1,6,344,1,66
8,13,12,2011,Сыктывкар-1,60,1,346,0,68
9,15,12,2011,Сыктывкар-1,96,3,348,0,70
10,16,12,2011,Сыктывкар-1,134,4,349,0,71
11,17,12,2011,Сыктывкар-1,112,5,350,1,72
12,18,12,2011,Сыктывкар-1,100,6,351,1,73
13,20,12,2011,Сыктывкар-1,73,1,353,0,75
14,21,12,2011,Сыктывкар-1,94,2,354,0,76
15,22,12,2011,Сыктывкар-1,94,3,355,0,77
16,23,12,2011,Сыктывкар-1,129,4,356,0,78
17,24,12,2011,Сыктывкар-1,164,5,357,1,79
18,25,12,2011,Сыктывкар-1,122,6,358,1,80
19,28,12,2011,Сыктывкар-1,128,2,361,0,83
20,29,12,2011,Сыктывкар-1,172,3,362,0,84
21,30,12,2011,Сыктывкар-1,223,4,363,0,85
22,31,12,2011,Сыктывкар-1,68,5,364,1,86
23,1,1,2012,Сыктывкар-1,100,6,0,1,87
24,2,1,2012,Сыктывкар-1,169,0,1,0,88
25,3,1,2012,Сыктывкар-1,142,1,2,0,89
26,4,1,2012,Сыктывкар-1,130,2,3,0,90
27,5,1,2012,Сыктывкар-1,119,3,4,0,91
28,6,1,2012,Сыктывкар-1,128,4,5,0,92
29,7,1,2012,Сыктывкар-1,128,5,6,1,93
...,...,...,...,...,...,...,...,...,...
46018,19,10,2016,Самара-1,240,2,292,0,1840
46019,19,10,2016,Уфа-1,98,2,292,0,1840
46020,19,10,2016,Челябинск-1,127,2,292,0,1840
46021,19,10,2016,Радужный-1,46,2,292,0,1840
46022,19,10,2016,Домодедово-1,65,2,292,0,1840
46023,19,10,2016,Балашиха-1,105,2,292,0,1840
46024,19,10,2016,Волжский-1,86,2,292,0,1840
46025,19,10,2016,Альметьевск-1,58,2,292,0,1840
46026,19,10,2016,Тюмень-2,117,2,292,0,1840
46027,19,10,2016,Абакан-1,56,2,292,0,1840
46028,19,10,2016,Саратов-1,178,2,292,0,1840
46029,19,10,2016,Новороссийск-1,125,2,292,0,1840
46030,19,10,2016,Выборг-1,81,2,292,0,1840
46031,19,10,2016,Екатеринбург-1,78,2,292,0,1840
46032,19,10,2016,Зеленокумск-1,36,2,292,0,1840
46033,19,10,2016,Реутов-1,95,2,292,0,1840
46034,19,10,2016,Самара-4,190,2,292,0,1840
46035,19,10,2016,Ульяновск-1,111,2,292,0,1840
46036,19,10,2016,Сыктывкар-4,33,2,292,0,1840
46037,19,10,2016,Зеленоград-1,139,2,292,0,1840
46038,19,10,2016,Москва 1-1,69,2,292,0,1840
46039,19,10,2016,Уссурийск-1,130,2,292,0,1840
46040,19,10,2016,Энгельс-1,48,2,292,0,1840
46041,19,10,2016,Абинск-1,43,2,292,0,1840
46042,19,10,2016,Смоленск-3,39,2,292,0,1840
46043,19,10,2016,Москва 1-5,75,2,292,0,1840
46044,19,10,2016,Чайковский-1,41,2,292,0,1840
46045,19,10,2016,Челябинск-2,134,2,292,0,1840
46046,19,10,2016,Ангарск-1,68,2,292,0,1840
46047,19,10,2016,Железнодорожный-1,105,2,292,0,1840

In [ ]:
train.to_csv("train.csv", index=None)
test.to_csv("test.csv", index=None)